name: "PNPM Install"
description: "Install dependencies with pnpm"

inputs:
  target:
    description: "The name of the directory where the install should run"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v6
      with:
        node-version: "24"
        registry-url: 'https://registry.npmjs.org'
    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: echo "path=$(pnpm store path)" >> "$GITHUB_OUTPUT"
    - name: Setup pnpm cache
      uses: actions/cache@v5
      with:
        path: ${{ steps.pnpm-store.outputs.path }}
        key: pnpm-store-${{ runner.os }}-${{ inputs.target }}-${{ hashFiles(format('{0}/pnpm-lock.yaml', inputs.target)) }}
        restore-keys: |
          pnpm-store-${{ runner.os }}-${{ inputs.target }}-
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.target }}
