name: "PNPM Install"
description: "Install dependencies with pnpm"

inputs:
  target:
    description: "The name of the directory where the install should run"
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v6
      with:
        node-version: "${{ env.NODE_VERSION }}"
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
      working-directory: ${{ inputs.target }}
