name: 'Brocolito'
description: 'Prepare Brocolito CLI'
inputs:
  dir:
    description: The directory where you have placed your CLI code.
    default: .github/cli

runs:
  using: composite
  steps:
    - uses: ./.github/actions/pnpm-install
      with:
        target: ${{ inputs.dir }}
    - run: |
        realpath build/bin >> $GITHUB_PATH
      shell: bash
      working-directory: ${{ inputs.dir }}
